In [1]:
import numpy as np

In [2]:
a = np.random.random((10,4))
print(a)

[[0.79117393 0.50498197 0.34724004 0.66214946]
 [0.40485767 0.01630873 0.65964645 0.69130847]
 [0.70786234 0.90255382 0.20639763 0.49015411]
 [0.74805942 0.68862878 0.30103593 0.21195972]
 [0.52021083 0.11000687 0.82275085 0.30737782]
 [0.47137144 0.35510304 0.75042162 0.6929952 ]
 [0.49711691 0.68518943 0.68834225 0.90050422]
 [0.69767368 0.36171533 0.49799284 0.19359057]
 [0.88082776 0.70037832 0.32067581 0.02152991]
 [0.98302266 0.27610497 0.91041363 0.40676196]]


In [3]:
type(a)

numpy.ndarray

In [4]:
print(a.shape)
print(a.size)

(10, 4)
40


In [5]:
print(np.random.rand(10))
print(np.random.randn(10))

[0.59988092 0.3676912  0.77080995 0.63510278 0.86478576 0.03591815
 0.73722276 0.33792407 0.63856534 0.9996965 ]
[ 0.54413271  1.23440762 -0.44649622 -0.76296034  0.97756419 -1.16503942
 -0.18694792 -1.24102202  0.69488022 -0.34154885]


In [6]:
np.random.seed(0) 

In [7]:
a[0,0]

0.7911739330596584

In [8]:
a[0]

array([0.79117393, 0.50498197, 0.34724004, 0.66214946])

In [9]:
a[0,:]

array([0.79117393, 0.50498197, 0.34724004, 0.66214946])

In [10]:
a[:,0]

array([0.79117393, 0.40485767, 0.70786234, 0.74805942, 0.52021083,
       0.47137144, 0.49711691, 0.69767368, 0.88082776, 0.98302266])