In [26]:
import numpy as np 
import random 

a = np.random.random((2,3,5))


b = np.full((5,3,2),1)


c = np.transpose(b)


d = np.add(a,c)
# print(a,'\n')

# print(d, '\n')

e = np.multiply(a,c)

# print(e, '\n')

d_mean = np.mean(d)
# print(d_mean)
# print(d_max)
# print(d_min)
d_max = np.max(d)
d_min = np.min(d)

f = np.full([2,3,5],"")

print(type(f[0][0][0]))
print(d)
print(d[1][0][0])


<class 'numpy.str_'>
[[[1.63989139 1.21337083 1.59121472 1.71774178 1.66571363]
  [1.07146834 1.63405907 1.80372424 1.65559842 1.65935463]
  [1.02055902 1.11230494 1.98079331 1.89285561 1.27613627]]

 [[1.69097215 1.02524223 1.60280553 1.95864361 1.97108597]
  [1.39720595 1.17553983 1.10866307 1.60232459 1.82902087]
  [1.73422943 1.12372197 1.23383206 1.84660495 1.70048192]]]
1.690972146218836


In [29]:

for a in range(len(d)):
    for i in range(len(d[a])):
        for j in range(len(d[a,i])):
            if d[a][i][j] > d_min and d[a][i][j] < d_mean:
                f[a][i][j] = 'B'
            elif d[a][i][j] > d_mean and d[a][i][j] < d_max:
                f[a][i][j] = 'D'
            elif d[a][i][j] == d_mean:
                f[a][i][j] = 'C'
            elif d[a][i][j] == d_min:
                f[a][i][j] = 'A'
            elif d[a][i][j] == d_max:
                f[a][i][j] = 'E'
            
print(f)



[[['D' 'B' 'D' 'D' 'D']
  ['B' 'D' 'D' 'D' 'D']
  ['A' 'B' 'E' 'D' 'B']]

 [['D' 'B' 'D' 'D' 'D']
  ['B' 'B' 'B' 'D' 'D']
  ['D' 'B' 'B' 'D' 'D']]]
