In [17]:
import numpy as np
a = np.random.random((10,4))
list(a)
float(a[0][0])



0.24261625186505043

In [20]:
print(type(a[0][0]/2))

<class 'numpy.float64'>


In [21]:
c = np.random.random((2,3,4,5))
print(c)


[[[[0.0140573  0.00434179 0.06497326 0.40603262 0.71618054]
   [0.45050678 0.19150023 0.85736654 0.14663463 0.44110124]
   [0.24772765 0.85819174 0.95206773 0.15665224 0.89174756]
   [0.35518797 0.8153879  0.94741733 0.55972283 0.37619646]]

  [[0.66703984 0.91878807 0.03470799 0.35236285 0.16802335]
   [0.55855628 0.61156598 0.99670966 0.45061009 0.44286467]
   [0.20596299 0.80959533 0.57320154 0.63631055 0.55575644]
   [0.32793255 0.2941605  0.46890742 0.23071931 0.58007795]]

  [[0.22158694 0.80366852 0.04264713 0.65201433 0.13412202]
   [0.66295293 0.83332764 0.25906344 0.180475   0.16580557]
   [0.15419053 0.84873707 0.2398204  0.85766118 0.90353037]
   [0.87170342 0.82526168 0.19321068 0.3543328  0.43985748]]]


 [[[0.6377673  0.81224062 0.96304506 0.48036538 0.51815461]
   [0.49123796 0.62127734 0.74817854 0.55023601 0.59448618]
   [0.71406095 0.25928595 0.64919894 0.66265174 0.05658511]
   [0.39109786 0.99582533 0.37631052 0.98354699 0.1202543 ]]

  [[0.33326824 0.30574881 0.00