In [1]:
import numpy as np 
import random 

a = np.random.random((2,3,5))


b = np.full((5,3,2),1)


c = np.transpose(b)


d = np.add(a,c)

In [2]:
e = np.multiply(a,c)

In [3]:
d_mean = np.mean(d)

In [4]:
d_max = np.max(d)
d_min = np.min(d)

In [5]:
f = np.zeros([2,3,5])

In [11]:
for a in range(len(d)):
    for i in range(len(d[a])):
        for j in range(len(d[a][i])):
            if d[a][i][j] > d_min and d[a][i][j] < d_mean:
                f[a][i][j] = 25
            elif d[a][i][j] > d_mean and d[a][i][j] < d_max:
                f[a][i][j] = 75
            elif d[a][i][j] == d_mean:
                f[a][i][j] = 50
            elif d[a][i][j] == d_min:
                f[a][i][j] = 0
            elif d[a][i][j] == d_max:
                f[a][i][j] = 100
print(d)
print(f)
            

[[[1.03417993 1.96410461 1.89701853 1.68587593 1.75444061]
  [1.77167905 1.56113095 1.99312875 1.77842559 1.91527643]
  [1.24793608 1.14723093 1.49228044 1.21958937 1.20979877]]

 [[1.56162478 1.87980589 1.2221157  1.94868763 1.60077371]
  [1.47436511 1.05972495 1.74804196 1.91939737 1.47082823]
  [1.78730863 1.80281217 1.79861798 1.13473347 1.62288594]]]
[[[  0.  75.  75.  75.  75.]
  [ 75.  25. 100.  75.  75.]
  [ 25.  25.  25.  25.  25.]]

 [[ 25.  75.  25.  75.  75.]
  [ 25.  25.  75.  75.  25.]
  [ 75.  75.  75.  25.  75.]]]
