In [11]:
import numpy as np
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [12]:
a[1, 5] #[00 01 02 03 04 05 06] or #[00 01 02 03 04 05 0-1] #Negative index will return the end of the array
        #[10 11 12 13 14 15 16] 

13

In [13]:
a[1, -2] ##End of array using negative

13

In [14]:
#Get a specific row 
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [15]:
#Get a specific column
a[:,2]

array([ 3, 10])

In [16]:
#Getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:6:2] #First row, index 1 to index 6 and stepping by 2

array([2, 4, 6])

In [17]:
a[1,5] = 20
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [18]:
a[:,2] = 5
a

array([[ 1,  2,  5,  4,  5,  6,  7],
       [ 8,  9,  5, 11, 12, 20, 14]])

In [20]:
#3d array
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [22]:
#to get a specific element of an array work outside in so pick out the 4
# b[0][1][1]
b[0,1,1]

4

In [23]:
b[:,1,:] = [[9,9],[8,8]]

In [24]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])