In [9]:
import numpy as np
#All 0s Matrix
a = np.zeros((2,3,3))
a

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [4]:
#All 1s Matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [5]:

np.full((2,2),99,dtype = 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [8]:
np.full_like(a,4)

array([[[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]],

       [[4., 4., 4.],
        [4., 4., 4.],
        [4., 4., 4.]]])

In [11]:
np.random.rand(4,2,3) #pass in the integers

array([[[0.51155895, 0.0560801 , 0.0513054 ],
        [0.26659679, 0.4832975 , 0.07111431]],

       [[0.16665528, 0.57757258, 0.9187142 ],
        [0.43223167, 0.92548469, 0.94657737]],

       [[0.91425176, 0.36477939, 0.83155622],
        [0.31283313, 0.49758302, 0.04330964]],

       [[0.25307444, 0.78153334, 0.9140327 ],
        [0.03362806, 0.32271671, 0.51390647]]])

In [17]:
#random integer values
np.random.random_sample(a.shape)
np.random.randint(25, size=(3,3))
np.random.randint(100, size=(3,3))

array([[16, 65, 42],
       [71, 74, 32],
       [12, 78,  2]])

In [19]:
#identity matrix
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [25]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
r2 = np.repeat(arr,3,axis=1)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [36]:
#Quick test
test = np.ones((5,5),dtype='int32')
z = np.zeros((3,3))
z[1][1]=9

z

test[1:4,1:4] = z
test

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [41]:
a = np.array([1,2,3])
# b = a #this is dangerous because if we change b it will change a...so instead of setting them directly equal we should use b.copy
print(b)

[1 2 3]


In [40]:
b = a.copy()
b

array([1, 2, 3])