In [2]:
import numpy as np

a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [3]:
a + 2

array([3, 4, 5, 6])

In [4]:
a - 2

array([-1,  0,  1,  2])

In [5]:
a * 2

array([2, 4, 6, 8])

In [7]:
(a / 2)

SyntaxError: invalid syntax (<ipython-input-7-2b1fdfcc2b88>, line 1)

In [8]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [9]:
a ** 2

array([ 1,  4,  9, 16], dtype=int32)

In [10]:
#take the sin
np.sin(a)
np.cos(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Linear Algebra


In [12]:
a = np.ones((2,3))
b = np.full((3,2),2)

In [18]:
# In LA the columns of the first one must equal the rows of the second
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [19]:
#finding the determinant of the identity matrix (Should be one)
c = np.identity(3)
np.linalg.det(c)

1.0

# go to https://docs.scipy.org/doc/numpy/refernece/routines.linalg.html

##### Statistics

In [20]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
#gives min of the first row and the min of the second row
np.min(stats,axis=1)

array([1, 4])

In [27]:
np.max(stats, axis = 1)

array([3, 6])

In [32]:
#sums everything
print(np.sum(stats))
#sums up the columns in the matrix
print(np.sum(stats, axis=0))
#sums up the rows in the matrix and returns a diff array
print(np.sum(stats, axis=1))

21
[5 7 9]
[ 6 15]


In [ ]:
np.sum(stats)