In [1]:
#Lists are slow 
#Numpy is fast.

#numpy uses fixed types and contiguous memory. Don't have to use as much memory with fixed types. Contiguous memory will allow for the blocks to sit next to each other. 

#In a list you can insert, delete, append, concatenate...

# a = [1,3,5]
# b = [1,2,3]
#a*b will return an error, but in numpy...

import numpy as np
a = np.array([1,3,5])
b = np.array([1,2,3])

print(a*b)


[ 1  6 15]


In [2]:
#applications of numpy

# Mathematics (Matlab Replacement)
# Plotting(Matplotlib)
# Backend(Pandas, Connect 4, Digital Photography)

a = np.array([1,2,3])
print(a)


[1 2 3]


In [5]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
b

array([[9., 8., 7.],
       [6., 5., 4.]])

In [7]:
#Get Dimension
a.ndim
b.ndim

2

In [11]:
#Get Shape
a.shape
b.shape

(2, 3)

In [16]:
#Get Type 
a.dtype
# b.dtype

dtype('int32')

In [17]:
#Get Size
a.itemsize #4 bytes...you can change the size 

4

In [18]:
#Get Total Size
a.size * a.itemsize #this will give you the same number as a.nbytes
a.nbytes #number of bytes

12