In [5]:
import numpy as np

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((4,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


## vertical stack

In [15]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack((v1,v2,v1,v2,v1,v1))

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [1, 2, 3, 4]])

## Horizontal Stack

In [16]:
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

## Load Data from File

In [22]:
filedata = np.genfromtxt('data.txt', delimiter= ',', dtype = 'int32')
filedata.astype('int32') #redundant but you can do it this way too
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  14,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

## Boolean Masking and Advanced Indexing

In [24]:
print(filedata > 50)

filedata[filedata>50]


[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]


array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [25]:
# you can index with a list in Numpy

a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]


array([2, 3, 9])

In [28]:
np.any(filedata>50)
np.any(filedata>50, axis=0)
np.any(filedata>50, axis=1)

array([ True,  True,  True])

In [33]:
print(filedata)
((filedata > 50) & (filedata < 100))

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  14  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [34]:
#for indexing you need the rows columns in that order


ValueError: only 2 non-keyword arguments accepted

In [58]:
a = np.ones((30,1))
a
for i in range(30):
    a[i] = i+1

print(a.reshape(6,5))

# print(a[0:2,2:4])
# print(a[[0,1,2,3],[1,2,3,4]])
# print(a[[0,4,5],3:])

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]
 [26. 27. 28. 29. 30.]]
