In [1]:
import numpy as np
print(np.__version__)

1.16.4


In [4]:
a = np.random.random([2,3,5])
print(a)

[[[0.7734496  0.48443852 0.12399255 0.8933886  0.73447545]
  [0.28115437 0.92792289 0.3265745  0.11068663 0.89856342]
  [0.75712902 0.80401089 0.51347435 0.93577708 0.23841688]]

 [[0.97262065 0.14636135 0.245201   0.82441566 0.44430673]
  [0.91542106 0.49380911 0.1485938  0.94737807 0.68253289]
  [0.76772837 0.21229681 0.95501834 0.86385289 0.47423332]]]
